updating ci/cd

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -46,15 +46,17 @@ jobs:
 
           echo "Pulling latest changes..."
           git pull || { echo "Git pull failed!"; exit 1; }
-          pwd
+          
           echo "Installing dependencies..."
-          npm install || { echo "Dependency installation failed!"; exit 1; }
+          pnpm install || { echo "Dependency installation failed!"; exit 1; }
 
           echo "Building application ..."
-          npm run build || { echo "Build failed!"; exit 1; }
+          pnpm run build || { echo "Build failed!"; exit 1; }
 
           echo "Restarting Docker services..."
           docker compose down || { echo "Failed to stop Docker services!"; exit 1; }
           docker compose up -d || { echo "Failed to start Docker services!"; exit 1; }
 
+          # echo "Restarting application with PM2..."
+          # npx pm2 restart ${{ secrets.APP_NAME }} || { echo "PM2 restart failed!"; exit 1; }
           ENDSSH
