updating ci/cd

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -48,11 +48,10 @@ jobs:
           git pull || { echo "Git pull failed!"; exit 1; }
 
           echo "Installing dependencies..."
-          npm install pnpm -g || { echo "Failed to install pnpm!"; exit 1; }
-          pnpm install || { echo "Dependency installation failed!"; exit 1; }
+          npm install || { echo "Dependency installation failed!"; exit 1; }
 
           echo "Building application ..."
-          pnpm run build || { echo "Build failed!"; exit 1; }
+          npm run build || { echo "Build failed!"; exit 1; }
 
           echo "Restarting Docker services..."
           docker compose down || { echo "Failed to stop Docker services!"; exit 1; }
