finished ci/cd

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -48,13 +48,16 @@ jobs:
           git pull || { echo "Git pull failed!"; exit 1; }
 
           echo "Installing dependencies..."
+          npm install pnpm -g || { echo "Failed to install pnpm!"; exit 1; }
           pnpm install || { echo "Dependency installation failed!"; exit 1; }
-          pnpm run build || { echo "Dependency installation failed!"; exit 1; }
+
+          echo "Building application ..."
+          pnpm run build || { echo "Build failed!"; exit 1; }
 
           echo "Restarting Docker services..."
           docker compose down || { echo "Failed to stop Docker services!"; exit 1; }
           docker compose up -d || { echo "Failed to start Docker services!"; exit 1; }
 
           echo "Restarting application with PM2..."
-          pm2 restart ${{ secrets.APP_NAME }} || { echo "PM2 restart failed!"; exit 1; }
+          npx pm2 restart ${{ secrets.APP_NAME }} || { echo "PM2 restart failed!"; exit 1; }
           ENDSSH
